base {
    archivesName = "polymer-sound-patcher"
}
version = rootProject.mod_version + "+" + rootProject.minecraft_version


sourceSets {
    testmod {
        runtimeClasspath += main.runtimeClasspath
        compileClasspath += main.compileClasspath
    }
}

loom {
    runs {
        testmodClient {
            client()
            ideConfigGenerated project.rootProject == project
            name = "(Blocks) Test Mod Client"
            source sourceSets.testmod
        }
        testmodServer {
            server()
            ideConfigGenerated project.rootProject == project
            name = "(Blocks) Test Mod Server"
            source sourceSets.testmod
        }
    }
}

dependencies {
    implementation(project(path: ':polymer-common'))
    implementation(project(path: ':polymer-resource-pack'))
    implementation(project(path: ':polymer-resource-pack-extras'))
    implementation(project(path: ':polymer-core'))

    testmodImplementation sourceSets.main.output
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}