# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
	# check these on https://fabricmc.net/use

minecraft_version=26.1.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Fabric API
fabric_api_version=0.144.3+26.1

maven_group = eu.pb4

mod_version = 0.16.2

mc_extra_supported=26.1

minecraft_version_supported = ">=1.21.11-"

is_stable = true
