# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
	# check these on https://fabricmc.net/use

minecraft_version=1.21.9-pre2
yarn_mappings=1.21.9-pre2+build.2
loader_version=0.17.2

# Fabric API
fabric_version=0.133.7+1.21.9

maven_group = eu.pb4

mod_version = 0.14.0-beta.1

minecraft_version_supported = ">=1.21.9-"

packet_tweaker_version = 0.6.0-pre.1+1.21.2-pre3

is_stable = false
