base.archivesName = "polymer-resource-pack-extras"
version = rootProject.mod_version + "+" + rootProject.minecraft_version
group = rootProject.maven_group

sourceSets {
    testmod {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
}

loom {

}

dependencies {
    modCompileOnly "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_version}"

    api (project(path: ':polymer-common', configuration: 'namedElements'))
    api (project(path: ':polymer-resource-pack', configuration: 'namedElements'))
}

afterEvaluate {
    // Disable the gen sources task on sub projects
    genSourcesWithFernFlower.enabled = true
    genSourcesWithCfr.enabled = false
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version_supported", rootProject.minecraft_version_supported

    filesMatching("fabric.mod.json") {
        expand "version": project.version
        expand "minecraft_version_supported": rootProject.minecraft_version_supported
    }
}