base {
    archivesName = "polymer-resource-pack-extras"
}
version = rootProject.mod_version + "+" + rootProject.minecraft_version
group = rootProject.maven_group

sourceSets {
    testmod {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
}

loom {

}

dependencies {
    api (project(path: ':polymer-common'))
    api (project(path: ':polymer-resource-pack'))
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version_supported", rootProject.minecraft_version_supported

    filesMatching("fabric.mod.json") {
        expand "version": project.version
        expand "minecraft_version_supported": rootProject.minecraft_version_supported
    }
}