base {
    archivesName = "polymer-common"
}
version = rootProject.mod_version + "+" + rootProject.minecraft_version
group = rootProject.maven_group


dependencies {
    compileOnly("org.geysermc.floodgate:api:2.2.0-SNAPSHOT") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    compileOnly("com.viaversion:viaversion-api:5.3.2") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    compileOnly("com.terraformersmc:modmenu:18.0.0-alpha.5") {
        exclude(group: "net.fabricmc.fabric-api")
    }
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version_supported", rootProject.minecraft_version_supported

    filesMatching("fabric.mod.json") {
        expand "version": project.version
        expand "minecraft_version_supported": rootProject.minecraft_version_supported
    }
}