base {
    archivesName = "polymer-autohost"
}
version = rootProject.mod_version + "+" + rootProject.minecraft_version


sourceSets {
    testmod {
        runtimeClasspath += main.runtimeClasspath
        compileClasspath += main.compileClasspath
    }
}

loom {
    runs {
        testmodServer {
            server()
            ideConfigGenerated project.rootProject == project
            name = "(AutoHost) Test Mod Server"
            source sourceSets.testmod
        }
    }
}

dependencies {
    api (project(path: ':polymer-common'))
    api (project(path: ':polymer-resource-pack'))


    testmodImplementation sourceSets.main.output
    testmodImplementation (project(path: ':polymer-core'))
    testmodImplementation (project(path: ':polymer-blocks'))
    testmodImplementation (project(path: ':polymer-reg-sync-manipulator'))
    testmodImplementation (project(path: ':polymer-networking'))
    testmodImplementation (project(path: ':polymer-resource-pack-extras'))
    testmodImplementation (project(path: ':polymer-sound-patcher'))

    compileOnly (project(path: ':polymer-virtual-entity'))
    localRuntime (project(path: ':polymer-virtual-entity'))
    compileOnly (project(path: ':polymer-resource-pack-extras'))
    localRuntime (project(path: ':polymer-resource-pack-extras'))
    compileOnly (project(path: ':polymer-sound-patcher'))
    localRuntime (project(path: ':polymer-sound-patcher'))
    //modLocalRuntime("xyz.nucleoid:server-translations-api:2.5.0+1.21.5-rc1") {
    //    exclude(group: "net.fabricmc.fabric-api")
    //}
    //api include('io.netty:netty-codec-http:4.1.82.Final')

    project(":polymer-core").afterEvaluate {
        testmodImplementation project(":polymer-core").sourceSets.testmod.output
    }
    project(":polymer-blocks").afterEvaluate {
        testmodImplementation project(":polymer-blocks").sourceSets.testmod.output
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}
