package eu.pb4.polymer.block;

import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.network.Packet;
import net.minecraft.network.packet.s2c.play.BlockEntityUpdateS2CPacket;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.math.BlockPos;

public interface VirtualHeadBlock extends VirtualBlock {
    /**
     * This method is used to determine texture/skin of client sided head
     * Player Skin can be generated by https://mineskin.org/
     *
     * @param state Server-side BlockState
     * @return Skin Value
     */
    String getVirtualHeadSkin(BlockState state);

    default Block getVirtualBlock() {
        return Blocks.PLAYER_HEAD;
    }

    /**
     * Creates tag of Skull block entity
     *
     * @param state Server-side BlockState
     * @return CompoundTag representing client-side
     */
    default CompoundTag getVirtualHeadSkullOwner(BlockState state) {
        CompoundTag skullOwner = new CompoundTag();
        CompoundTag properties = new CompoundTag();
        CompoundTag data = new CompoundTag();
        ListTag textures = new ListTag();
        textures.add(data);

        data.putString("Value", ((VirtualHeadBlock) state.getBlock()).getVirtualHeadSkin(state));
        properties.put("textures", textures);
        skullOwner.put("Properties", properties);
        skullOwner.putIntArray("Id", new int[] { 0, 0, 0, 0 });

        return skullOwner;
    }

    /**
     * Creates client-side skull BlockEntity
     *
     * @param state Server-side BlockState
     * @param pos Block's position
     * @return A Packet
     */
    default Packet<?> getVirtualHeadPacket(BlockState state, BlockPos pos) {
        CompoundTag main = new CompoundTag();
        CompoundTag skullOwner = this.getVirtualHeadSkullOwner(state);
        main.putString("id", "minecraft:skull");
        main.put("SkullOwner", skullOwner);
        main.putInt("x", pos.getX());
        main.putInt("y", pos.getY());
        main.putInt("z", pos.getZ());
        return new BlockEntityUpdateS2CPacket(pos, 4, main);
    }

    default void sendPacketsAfterCreation(ServerPlayerEntity player, BlockPos pos, BlockState blockState) {
        player.networkHandler.sendPacket(((VirtualHeadBlock) blockState.getBlock()).getVirtualHeadPacket(blockState, pos));
    }

}
