package eu.pb4.polymer.core.api.block;

import eu.pb4.polymer.core.api.utils.PolymerUtils;
import net.minecraft.core.BlockPos;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.NbtOps;
import net.minecraft.network.protocol.Packet;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.item.component.ResolvableProfile;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockState;
import net.fabricmc.fabric.api.networking.v1.context.PacketContext;
import org.jspecify.annotations.Nullable;

public interface PolymerHeadBlock extends PolymerBlock {
    /**
     * This method is used to determine texture/skin of client sided head
     * Player Skin can be generated by https://mineskin.org/
     *
     * @param state Server-side BlockState
     * @param pos
     * @param context
     * @return Skin Value
     */
    String getPolymerSkinValue(BlockState state, BlockPos pos, PacketContext context);
    default String getPolymerSkinSignature(BlockState state, BlockPos pos, PacketContext context) {
        return null;
    };

    @Override
    default BlockState getPolymerBlockState(BlockState state, @Nullable PacketContext context) {
        return Blocks.PLAYER_HEAD.defaultBlockState();
    }

    /**
     * Creates client-side skull BlockEntity
     *
     * @param state Server-side BlockState
     * @param pos Block's position
     * @return A Packet
     */
    default Packet<?> getPolymerHeadPacket(BlockState state, BlockPos pos, PacketContext context) {
        CompoundTag main = new CompoundTag();
        main.putString("id", "minecraft:skull");
        main.put("profile", ResolvableProfile.CODEC.encodeStart(NbtOps.INSTANCE,
                PolymerUtils.createProfileComponent(getPolymerSkinValue(state, pos, context),
                        getPolymerSkinSignature(state, pos, context))).result().get());
        main.putInt("x", pos.getX());
        main.putInt("y", pos.getY());
        main.putInt("z", pos.getZ());
        return PolymerBlockUtils.createBlockEntityPacket(pos, BlockEntityType.SKULL, main);
    }

    @Override
    default void onPolymerBlockSend(BlockState blockState, BlockPos.MutableBlockPos pos, ServerPlayer context) {
        context.connection.send(this.getPolymerHeadPacket(blockState, pos.immutable(), context.connection.getPacketContext()));
    }
}
