base {
    archivesName = "polymer-networking"
}
version = rootProject.mod_version + "+" + rootProject.minecraft_version
group = rootProject.maven_group


dependencies {
    api project(path: ':polymer-common')
    include(project(path: ':polymer-common'))
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version_supported", rootProject.minecraft_version_supported

    filesMatching("fabric.mod.json") {
        expand "version": project.version
        expand "minecraft_version_supported": rootProject.minecraft_version_supported
    }
}