package eu.pb4.polymer.api.block;

import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.nbt.NbtCompound;
import net.minecraft.nbt.NbtList;
import net.minecraft.network.Packet;
import net.minecraft.network.packet.s2c.play.BlockEntityUpdateS2CPacket;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.math.BlockPos;

public interface PolymerHeadBlock extends PolymerBlock {
    /**
     * This method is used to determine texture/skin of client sided head
     * Player Skin can be generated by https://mineskin.org/
     *
     * @param state Server-side BlockState
     * @return Skin Value
     */
    String getPolymerSkinValue(BlockState state);

    default Block getPolymerBlock() {
        return Blocks.PLAYER_HEAD;
    }

    /**
     * Creates tag of Skull block entity
     *
     * @param state Server-side BlockState
     * @return NbtCompound representing client-side
     */
    default NbtCompound getPolymerHeadSkullOwner(BlockState state) {
        NbtCompound skullOwner = new NbtCompound();
        NbtCompound properties = new NbtCompound();
        NbtCompound data = new NbtCompound();
        NbtList textures = new NbtList();
        textures.add(data);

        data.putString("Value", ((PolymerHeadBlock) state.getBlock()).getPolymerSkinValue(state));
        properties.put("textures", textures);
        skullOwner.put("Properties", properties);
        skullOwner.putIntArray("Id", new int[] { 0, 0, 0, 0 });

        return skullOwner;
    }

    /**
     * Creates client-side skull BlockEntity
     *
     * @param state Server-side BlockState
     * @param pos Block's position
     * @return A Packet
     */
    default Packet<?> getPolymerHeadPacket(BlockState state, BlockPos pos) {
        NbtCompound main = new NbtCompound();
        NbtCompound skullOwner = this.getPolymerHeadSkullOwner(state);
        main.putString("id", "minecraft:skull");
        main.put("SkullOwner", skullOwner);
        main.putInt("x", pos.getX());
        main.putInt("y", pos.getY());
        main.putInt("z", pos.getZ());
        return new BlockEntityUpdateS2CPacket(pos, BlockEntityUpdateS2CPacket.SKULL, main);
    }

    default void onPolymerBlockSend(ServerPlayerEntity player, BlockPos pos, BlockState blockState) {
        player.networkHandler.sendPacket(this.getPolymerHeadPacket(blockState, pos));
    }
}
